openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
info:
  description: This is a simple API
  version: "1.0.0"
  title: employees API
paths:
  /api/employees/{empId}:
    get:
      tags:
        - employees
      summary: find employee by id
      operationId: findEmployeeById
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: path
          name: empId
          description: pass in the required employee id
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Employee document found
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Server exception
        "501":
          description: MongoDB Exceptionw